/* VocabTime - Data & LocalStorage Management */

// 167 từ vựng gốc trích xuất từ tài liệu tu_vung.docx
const initialVocabularyList = [
  { en: "Business Administration", vi: "Quản trị Kinh doanh" },
  { en: "combines", vi: "kết hợp" },
  { en: "finance", vi: "tài chính" },
  { en: "fascinating", vi: "hấp dẫn, thú vị" },
  { en: "honestly", vi: "thành thật mà nói" },
  { en: "so far", vi: "cho đến nay" },
  { en: "semester", vi: "học kỳ" },
  { en: "disappointing", vi: "đáng thất vọng" },
  { en: "decision", vi: "quyết định" },
  { en: "consider", vi: "cân nhắc, xem xét" },
  { en: "found out", vi: "phát hiện ra" },
  { en: "revising", vi: "ôn tập, sửa lại" },
  { en: "regarding", vi: "liên quan đến, về việc" },
  { en: "recent announcement", vi: "thông báo gần đây" },
  { en: "unexpected", vi: "bất ngờ, không lường trước" },
  { en: "circumstances", vi: "hoàn cảnh" },
  { en: "adjustments", vi: "sự điều chỉnh" },
  { en: "appreciate", vi: "đánh giá cao, biết ơn" },
  { en: "informing", vi: "thông báo" },
  { en: "in advance", vi: "trước, báo trước" },
  { en: "kindly", vi: "vui lòng, xin hãy" },
  { en: "whether", vi: "liệu rằng, có... hay không" },
  { en: "possible", vi: "có thể" },
  { en: "provide additional", vi: "cung cấp thêm" },
  { en: "sessions", vi: "các buổi (học/họp)" },
  { en: "perform", vi: "biểu diễn, thực hiện" },
  { en: "regards", vi: "lời chào trân trọng" },
  { en: "blockbuster", vi: "phim bom tấn" },
  { en: "positive messages", vi: "thông điệp tích cực" },
  { en: "humour", vi: "sự hài hước" },
  { en: "the whole film", vi: "toàn bộ bộ phim" },
  { en: "virtual", vi: "ảo, trực tuyến" },
  { en: "repaired", vi: "được sửa chữa" },
  { en: "alternative", vi: "sự thay thế, phương án khác" },
  { en: "response", vi: "phản hồi" },
  { en: "organising", vi: "tổ chức" },
  { en: "discussion", vi: "cuộc thảo luận" },
  { en: "engaged", vi: "tham gia tích cực, bị thu hút" },
  { en: "attract", vi: "thu hút" },
  { en: "forward", vi: "chuyển tiếp; mong chờ (look forward)" },
  { en: "especially", vi: "đặc biệt là" },
  { en: "curious", vi: "tò mò" },
  { en: "convenient to carry", vi: "tiện lợi để mang theo" },
  { en: "expect", vi: "mong đợi" },
  { en: "deliveries", vi: "việc giao hàng" },
  { en: "disappointed", vi: "thất vọng" },
  { en: "upcoming", vi: "sắp tới" },
  { en: "recommendations", vi: "lời đề xuất, gợi ý" },
  { en: "encourage", vi: "khuyến khích" },
  { en: "swap", vi: "trao đổi, đổi" },
  { en: "amazed", vi: "kinh ngạc" },
  { en: "passion", vi: "niềm đam mê" },
  { en: "critic", vi: "nhà phê bình" },
  { en: "unfortunately", vi: "thật không may" },
  { en: "secretary", vi: "thư ký" },
  { en: "preference", vi: "sự ưu tiên, sở thích" },
  { en: "usual", vi: "thường lệ, như thường" },
  { en: "postponed", vi: "bị hoãn lại" },
  { en: "eventually", vi: "cuối cùng" },
  { en: "unavoidable", vi: "không thể tránh khỏi" },
  { en: "tends", vi: "có xu hướng" },
  { en: "busier", vi: "bận rộn hơn" },
  { en: "relevant", vi: "liên quan, có liên hệ" },
  { en: "opinions actively", vi: "tích cực đóng góp ý kiến" },
  { en: "swirling", vi: "xoáy, cuộn (ý tưởng...)" },
  { en: "inspired", vi: "được truyền cảm hứng" },
  { en: "sketchbook", vi: "sổ phác thảo" },
  { en: "reminds", vi: "nhắc nhở, gợi nhớ" },
  { en: "proper", vi: "đúng đắn, phù hợp" },
  { en: "techniques", vi: "kỹ thuật" },
  { en: "express", vi: "diễn đạt, thể hiện" },
  { en: "permission", vi: "sự cho phép" },
  { en: "mixed-media artist", vi: "nghệ sĩ đa chất liệu" },
  { en: "appeal", vi: "sự hấp dẫn, thu hút" },
  { en: "elderly", vi: "người cao tuổi" },
  { en: "rather", vi: "khá là, thay vào đó" },
  { en: "attendees", vi: "người tham dự" },
  { en: "themselves", vi: "chính họ, bản thân họ" },
  { en: "clients", vi: "khách hàng" },
  { en: "gladly", vi: "sẵn lòng, vui vẻ" },
  { en: "evolving", vi: "đang phát triển, thay đổi" },
  { en: "reflect", vi: "phản ánh" },
  { en: "stricter", vi: "nghiêm ngặt hơn" },
  { en: "terms", vi: "điều khoản" },
  { en: "confusion", vi: "sự bối rối, nhầm lẫn" },
  { en: "guidelines", vi: "hướng dẫn, quy định" },
  { en: "consistency", vi: "tính nhất quán" },
  { en: "generational gaps", vi: "khoảng cách thế hệ" },
  { en: "stability", vi: "sự ổn định" },
  { en: "embrace", vi: "đón nhận, chấp nhận" },
  { en: "session", vi: "buổi (học/họp)" },
  { en: "heated conversations", vi: "cuộc trò chuyện gay gắt" },
  { en: "occasionally", vi: "thỉnh thoảng" },
  { en: "speech beforehand", vi: "bài phát biểu trước đó" },
  { en: "perspectives", vi: "quan điểm, góc nhìn" },
  { en: "conclusions", vi: "kết luận" },
  { en: "debating", vi: "tranh luận" },
  { en: "casual", vi: "thoải mái, không trang trọng" },
  { en: "intimidating", vi: "gây e ngại, đáng sợ" },
  { en: "discourages", vi: "làm nản lòng" },
  { en: "light-hearted", vi: "vui vẻ, nhẹ nhàng" },
  { en: "political", vi: "thuộc về chính trị" },
  { en: "certificates", vi: "chứng chỉ" },
  { en: "rewarding", vi: "xứng đáng, bổ ích" },
  { en: "immersed", vi: "đắm chìm, hòa mình vào" },
  { en: "the ongoing", vi: "đang diễn ra, liên tục" },
  { en: "frustration", vi: "sự thất vọng, bực bội" },
  { en: "disturbs", vi: "làm phiền, quấy rầy" },
  { en: "pouches", vi: "túi nhỏ" },
  { en: "strict", vi: "nghiêm khắc" },
  { en: "outright", vi: "hoàn toàn, thẳng thừng" },
  { en: "patient", vi: "kiên nhẫn" },
  { en: "eyesight", vi: "thị lực" },
  { en: "moderately", vi: "vừa phải, ở mức độ vừa" },
  { en: "forum", vi: "diễn đàn" },
  { en: "essential", vi: "thiết yếu, cần thiết" },
  { en: "suitable", vi: "phù hợp" },
  { en: "facilities", vi: "cơ sở vật chất" },
  { en: "instructors", vi: "người hướng dẫn" },
  { en: "regularly", vi: "thường xuyên" },
  { en: "concerned", vi: "lo lắng, quan tâm" },
  { en: "perhaps", vi: "có lẽ" },
  { en: "temporary", vi: "tạm thời" },
  { en: "substitute", vi: "người/vật thay thế" },
  { en: "consultant", vi: "nhà tư vấn" },
  { en: "definitely", vi: "chắc chắn" },
  { en: "utilities", vi: "tiện ích (điện, nước...)" },
  { en: "allowed", vi: "được phép" },
  { en: "decide to rent", vi: "quyết định thuê" },
  { en: "satisfied", vi: "hài lòng" },
  { en: "spacious", vi: "rộng rãi" },
  { en: "downside", vi: "mặt hạn chế, nhược điểm" },
  { en: "appointment", vi: "cuộc hẹn" },
  { en: "recently", vi: "gần đây" },
  { en: "property", vi: "bất động sản" },
  { en: "mention", vi: "đề cập" },
  { en: "grateful", vi: "biết ơn" },
  { en: "look forward", vi: "mong chờ" },
  { en: "interior", vi: "nội thất" },
  { en: "fortunately", vi: "may mắn thay" },
  { en: "frustrating", vi: "gây khó chịu, bực bội" },
  { en: "inconsiderate", vi: "thiếu chu đáo, vô ý" },
  { en: "energy-efficient", vi: "tiết kiệm năng lượng" },
  { en: "maintenance", vi: "bảo trì, bảo dưỡng" },
  { en: "lack", vi: "thiếu hụt" },
  { en: "proper insulation", vi: "cách nhiệt đúng cách" },
  { en: "sustainable", vi: "bền vững" },
  { en: "long-term", vi: "dài hạn" },
  { en: "proposal", vi: "đề xuất" },
  { en: "knock down", vi: "phá bỏ, đập bỏ" },
  { en: "character", vi: "đặc trưng, nét riêng" },
  { en: "proposed", vi: "được đề xuất" },
  { en: "demolished", vi: "bị phá bỏ, bị dỡ bỏ" },
  { en: "compromise", vi: "sự thỏa hiệp" },
  { en: "condition", vi: "tình trạng, điều kiện" },
  { en: "significance", vi: "ý nghĩa, tầm quan trọng" },
  { en: "renovated", vi: "được cải tạo, tân trang" },
  { en: "organise", vi: "tổ chức" },
  { en: "survey", vi: "khảo sát" },
  { en: "gather", vi: "thu thập, tập hợp" },
  { en: "wooden bench", vi: "ghế băng gỗ" },
  { en: "herbs", vi: "các loại thảo mộc" },
  { en: "groceries", vi: "hàng tạp hóa, thực phẩm" },
  { en: "recovers", vi: "hồi phục" },
  { en: "replacements", vi: "sự thay thế, đồ thay thế" },
  { en: "sensible solution", vi: "giải pháp hợp lý" },
  { en: "energetic afterwards", vi: "tràn đầy năng lượng sau đó" },
  { en: "jogging", vi: "chạy bộ" },
  { en: "stretching", vi: "giãn cơ, kéo giãn" },
  { en: "struggle", vi: "vật lộn, đấu tranh" },
  { en: "lazier", vi: "lười hơn" },
  { en: "depends on", vi: "phụ thuộc vào" },
  { en: "individuals", vi: "cá nhân" },
  { en: "sponsorship", vi: "sự tài trợ" },
  { en: "burden", vi: "gánh nặng" },
  { en: "partnering", vi: "hợp tác" },
  { en: "advertising", vi: "quảng cáo" },
  { en: "exchange for funding", vi: "đổi lấy nguồn tài trợ" },
  { en: "alternatively", vi: "hoặc là, cách khác" },
  { en: "gradual", vi: "dần dần" },
  { en: "fundraising", vi: "gây quỹ" },
  { en: "constraints", vi: "hạn chế, ràng buộc" },
  { en: "primarily", vi: "chủ yếu" },
  { en: "refreshments", vi: "đồ ăn nhẹ, giải khát" },
  { en: "vending machine", vi: "máy bán hàng tự động" },
  { en: "intense workouts", vi: "buổi tập cường độ cao" },
  { en: "literature exhibition", vi: "triển lãm văn học" },
  { en: "authors", vi: "tác giả" },
  { en: "cherished", vi: "được trân trọng, yêu quý" },
  { en: "heartfelt storytelling", vi: "lối kể chuyện chân thành" },
  { en: "various", vi: "đa dạng, nhiều loại" },
  { en: "excerpts", vi: "đoạn trích" },
  { en: "particularly", vi: "đặc biệt là" },
  { en: "interview", vi: "phỏng vấn" },
  { en: "appealing", vi: "hấp dẫn, thu hút" },
  { en: "abroad", vi: "ở nước ngoài" },
  { en: "lecture", vi: "bài giảng" },
  { en: "expressing", vi: "bày tỏ, diễn đạt" },
  { en: "desire", vi: "mong muốn, khao khát" },
  { en: "effectively", vi: "một cách hiệu quả" },
  { en: "exchange", vi: "trao đổi" },
  { en: "learning journey", vi: "hành trình học tập" },
  { en: "relatable", vi: "dễ đồng cảm, gần gũi" },
  { en: "encouraging", vi: "khích lệ, động viên" },
  { en: "register", vi: "đăng ký" },
  { en: "concerning", vi: "liên quan đến, đáng lo ngại" },
  { en: "In addition", vi: "thêm vào đó" },
  { en: "sincerely", vi: "chân thành" },
  { en: "efforts", vi: "nỗ lực" },
  { en: "sacrifices", vi: "sự hy sinh" },
  { en: "behalf", vi: "đại diện cho (on behalf of)" },
  { en: "enrolled", vi: "đã đăng ký, đã ghi danh" },
  { en: "the dumps", vi: "tâm trạng chán nản (down in the dumps)" },
  { en: "struggling", vi: "đang vật lộn, đang chật vật" },
  { en: "commit", vi: "cam kết" },
  { en: "hitting", vi: "đạt tới, chạm tới" },
  { en: "enroll", vi: "đăng ký, ghi danh" },
  { en: "the bottom", vi: "đáy, mức thấp nhất" },
  { en: "assistance", vi: "sự hỗ trợ" },
  { en: "bowl", vi: "bát, tô" },
  { en: "nutritious", vi: "bổ dưỡng" },
  { en: "takeaway food", vi: "đồ ăn mang đi" },
  { en: "instant", vi: "ăn liền, tức thì" },
  { en: "independence", vi: "sự độc lập" },
  { en: "entire life", vi: "cả cuộc đời" },
  { en: "trendy recipes", vi: "công thức nấu ăn thịnh hành" },
  { en: "issue", vi: "vấn đề" },
  { en: "recipes", vi: "công thức nấu ăn" },
  { en: "preferences", vi: "sở thích, ưu tiên" },
  { en: "represent", vi: "đại diện cho" },
  { en: "heritage", vi: "di sản" },
  { en: "demolishing", vi: "việc phá bỏ, đang phá bỏ" },
  { en: "loan", vi: "khoản vay" },
  { en: "contribute", vi: "đóng góp" },
  { en: "compile", vi: "biên soạn, tổng hợp" },
  { en: "affordable", vi: "có giá cả phải chăng" },
  { en: "financial advisor", vi: "cố vấn tài chính" },
  { en: "mortgage", vi: "khoản vay thế chấp" },
  { en: "schemes", vi: "kế hoạch, chương trình" },
  { en: "artefacts", vi: "hiện vật" },
  { en: "truly", vi: "thực sự" },
  { en: "entry", vi: "lượt vào, mục nhập" },
  { en: "funding", vi: "nguồn tài trợ" },
  { en: "considered", vi: "được cân nhắc, được xem là" },
  { en: "discourage", vi: "làm nản lòng, ngăn cản" },
  { en: "low-income", vi: "thu nhập thấp" },
  { en: "accessibility", vi: "khả năng tiếp cận" },
  { en: "finalising", vi: "hoàn thiện, chốt lại" },
  { en: "energetic", vi: "tràn đầy năng lượng" },
  { en: "capturing", vi: "ghi lại, nắm bắt" },
  { en: "candid", vi: "tự nhiên, chân thực (ảnh không dàn dựng)" },
  { en: "potential", vi: "tiềm năng" },
  { en: "minimal", vi: "tối giản, ở mức tối thiểu" },
  { en: "cluttered", vi: "bừa bộn, lộn xộn" }
];

// Persistent State loaded from LocalStorage
let vocabList = JSON.parse(localStorage.getItem('vt_vocabList')) || initialVocabularyList;
let starredWords = new Set(JSON.parse(localStorage.getItem('vt_starredWords')) || []);
let typeCorrectTotal = parseInt(localStorage.getItem('vt_typeCorrect')) || 0;

// Smart Unlocked Scope: Track words reached via Flashcard mode
const MIN_UNLOCKED = 6;
let maxUnlockedIndex = parseInt(localStorage.getItem('vt_maxUnlockedIndex')) || (MIN_UNLOCKED - 1);
if (isNaN(maxUnlockedIndex) || maxUnlockedIndex < MIN_UNLOCKED - 1) {
  maxUnlockedIndex = MIN_UNLOCKED - 1;
}

let unlockedWordsSet = new Set(JSON.parse(localStorage.getItem('vt_unlockedWordsSet')) || []);
if (unlockedWordsSet.size < MIN_UNLOCKED) {
  vocabList.slice(0, Math.max(MIN_UNLOCKED, maxUnlockedIndex + 1)).forEach(w => unlockedWordsSet.add(w.en));
}

let globalScope = localStorage.getItem('vt_scope') || 'unlocked';

// Utility functions
function shuffle(arr) {
  const clone = [...arr];
  for (let i = clone.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [clone[i], clone[j]] = [clone[j], clone[i]];
  }
  return clone;
}

function cleanWord(str) {
  return str.toLowerCase().trim().replace(/['’]/g, "'").replace(/\s+/g, ' ');
}

function saveAllData() {
  localStorage.setItem('vt_vocabList', JSON.stringify(vocabList));
  localStorage.setItem('vt_unlockedWordsSet', JSON.stringify([...unlockedWordsSet]));
  if (typeof flashcardDeck !== 'undefined') {
    flashcardDeck = [...vocabList];
  }
  if (typeof updateStatsUI === 'function') {
    updateStatsUI();
  }
  if (typeof saveUserProgressToCloud === 'function' && typeof currentUser !== 'undefined' && currentUser) {
    saveUserProgressToCloud();
  }
}

function showToast(text) {
  const toast = document.createElement('div');
  toast.className = "fixed bottom-5 left-1/2 -translate-x-1/2 bg-slate-900 text-white font-extrabold text-xs px-4 py-2.5 rounded-2xl shadow-xl z-50 border border-slate-700 flex items-center gap-2";
  toast.innerHTML = `<i class="fa-solid fa-circle-info text-vtPurple"></i> <span>${text}</span>`;
  document.body.appendChild(toast);
  setTimeout(() => toast.remove(), 3000);
}
